# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b593e273dad0d701e27f66c44963f0686abfc1b2677aa86c6d4532de6a1f222471b32527ed82eaeda823d0363485c9247c5fff9b9b13e6cec92f492c438767f3

test:
  secret_key_base: 097c66ee41a0c29c56f9c84072e3afb51aea7dd2ecb29a300f495f75ceabe80a2a055ed8f91856cb13651c7cc3604be34552ac465906b459948ddabbfb1f6a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
